### PR TITLE
qtcreator: add project-update makefile target

### PR DESCRIPTION
**Pull request by belm0**

### CODE REVIEW

**Comment by belm0** [comment]
Actually it doesn't work consistently.  Especially handling of platformio.config is very mysterious.  It seems to remember old defines that were removed from platformio.ini.

**Comment by belm0** [comment]
> Especially handling of platformio.config is very mysterious. It seems to remember old defines that were removed from platformio.ini.

It only works if I delete `.pio/` first.  It has something to do with `idedata.json`, there is an unwanted feedback loop.

**Comment by belm0** [comment]
@ivankravets I think this PR was closed unintentionally, since we still want the `project-update` target added

**Comment by ivankravets** [comment]
Oh, yes, sorry. Please remove that part that removes .pio internals.

**Pull request merged**
