### PR TITLE
Added support for templated methods in InoToCPPConverter

### PR DESCRIPTION
**Pull request by xoseperez**
The InoToCPPConverter class does not match templated methods, like for instance this one:
```
template<typename T> bool setSetting(const String& key, T value) {
    return Embedis::set(key, String(value));
}
```

### CODE REVIEW

**Comment by ivankravets** [comment]
Hi,

Thank you! Could you provide a test for this PR?

* https://github.com/platformio/platformio-core/blob/develop/tests/test_ino2cpp.py
* https://github.com/platformio/platformio-core/tree/develop/tests/ino2cpp

You can run a test using `py.test -v -s tests/test_ino2cpp.py` command from a root of project.

**Comment by ivankravets** [comment]
Also, please [sign the Contributor License Agreement](https://www.clahub.com/agreements/platformio/platformio).

Thanks!

**Comment by xoseperez** [comment]
Can't sign the CLA. It says "We're sorry, but something went wrong"...

**Comment by ivankravets** [comment]
Could you try this link?

* https://www.clahub.com/agreements/platformio/platformio-core

**Comment by xoseperez** [comment]
Done, CLA signed.

**Comment by ivankravets** [comment]
Thanks a lot!

**Comment by eric-wieser** [comment]
I don't think templates methods like that work properly in the Arduino ide either...

**Pull request merged**
