### PR TITLE
device monitor: more graceful exit on disconnect

### LINKED ISSUE #3939: Serial Monitor should handle disconnects more gracefully
**_Edit from maintainers -_** Temporary solution: https://docs.platformio.org/en/latest/faq/advanced-serial-monitor.html

----------

# Serial Monitor should handle disconnects more gracefully

This is a bug report/feature request to improve the serial port functionality in Platform IO.

### Configuration

**Operating system**: Windows 10 x64

**PlatformIO Version** (`platformio --version`): `PlatformIO Core, version 5.1.1`

### Description of problem
Using serial monitor on a USB based serial port crashes with Exception

#### Steps to Reproduce

1. Start a serial monitor to a device with a USB based serial port: `pio device monitor`
2. Reset the device

### Actual Results
```log
Exception in thread rx:
Traceback (most recent call last):
  File "C:\Users\camer\.platformio\python3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\camer\.platformio\python3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\camer\.platformio\penv\lib\site-packages\serial\tools\miniterm.py", line 445, in reader
    data = self.serial.read(self.serial.in_waiting or 1)
  File "c:\users\camer\.platformio\penv\lib\site-packages\serial\serialwin32.py", line 257, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (PermissionError(13, 'The device does not recognize the command.', None, 22))
```

### Expected Results
An error message designed for a novice user to understand.

Ideally also (optional) automatic reconnect when the device comes back.

### PR DESCRIPTION
**Pull request by belm0**
Fixes #3939

```
$ pio device monitor
--- Available filters and text transformations: colorize, debug, default, direct, nocontrol, printable
--- More details at https://bit.ly/pio-monitor-filters
--- Miniterm on /dev/cu.wchusbserial51850172701  115200,8,N,1 ---
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---
fps:  64.4,  render:  1.0 ms
fps:  64.4,  render:  1.0 ms
fps:  64.4,  render:  1.0 ms
fps:  64.4,  render:  1.0 ms
--- receive exception ---

--- exit ---
```

### CODE REVIEW

**Comment by belm0** [comment]
I'll make a small change to honor `--quiet`

**Comment by ivankravets** [comment]
Sorry, I don't think we will be able to merge it. We support multiple versions of PySerial. We don't plan to maintain this part of 3rd party code in future PlatformIO releases.

If we can import the original miniterm code and "mock" some parts, it could make sense.

**Comment by belm0** [comment]
This PR doesn't constrain the version of pyserial used by platformio.  As long as the API used by the miniterm module is available, it's fine.

**Comment by ivankravets** [comment]
How about importing the existing miniterm module and mocking only specific functions? Python allows this.

```python
from serial  import Miniterm

Miniterm.dump_port_settings = mocked_func
```

**Comment by belm0** [comment]
> How about importing the existing miniterm module and mocking only specific functions?

That would be contrary to the goal you stated.  By monkey-patching the library's miniterm, the result will be tightly bound to a specific version range of pyserial, and likely to break in the future.  It's better to copy the code that is using the public API.  (I don't expect the API to be broken trivially, given the number of pyserial users.)

Imagine if the pyserial author had never put miniterm into the library, and just left it in the examples directory.  Wouldn't platformio have just used that as a reference point to get the job done?

**Comment by ivankravets** [comment]
Thanks again for the PR! I've finally found time and refactored the device monitor module. See https://github.com/platformio/platformio-core/commit/7f351bc7c8840aa4150d0ebc9000f17b3c0f2af4

Please re-test with `pio upgrade --dev`.

**Pull request closed without merging**
