### PR TITLE
Feature/azure devops default prefix

### PR DESCRIPTION
**Pull request by Granjow**
When cloning from Azure DevOps with the HTTPS URL copied from the *clone* tab, installation fails because PlatformIO downloads the HTML file instead of using the HTTPS protocol.

This PR prefixes Azure DevOps URLs with `+git`.

### CODE REVIEW

**Comment by ivankravets** [comment]
Could you check https://docs.platformio.org/en/latest/core/userguide/platforms/cmd_install.html#git ?

**Comment by Granjow** [comment]
@ivankravets Missed this content so far – thanks for the link.

In that case I suggest as alternative to output a hint that `git+` (or similar) might be missing when unpacking from an HTTPS? url fails. Would you agree with that change?

**Comment by ivankravets** [comment]
How does look the final Azure DevOps URL? Do they provide a normalized URL? We try to be service-independent. That is a reason why we created documentation and described how to use it with other source code platforms. See https://github.com/platformio/platformio-core/blob/develop/tests/package/test_meta.py#L134

**Comment by Granjow** [comment]
It is of the form `https://org@dev.azure.com/org/project/_git/repo`.

Yes, I see that and it makes sense to me, therefore outputting a warning would probably help more users to fix the URL than just Azure DevOps users.

**Comment by ivankravets** [comment]
This is the first case for the last 7 years. Let us see in the future. If someone will report similar issue, we implement a special autodetection for the Azure DevOps service. 

P.S: Thanks for using PlatformIO and your PR! 🙏

**Pull request closed without merging**
