### PR TITLE
Support for switching between multiple environments in VSCode

### PR DESCRIPTION
**Pull request by drzony**
This commit changes the way c_cpp_properties.json is generated, creating a separate build
configuration for each environment. This allows to select an environment using VSCode "build
configurations" option

### CODE REVIEW

**Comment by drzony** [comment]
This is my initial proposition, however it changes the default behavior of the `pio init` command, so some changes may be required.
Original: When `pio init` is used without `-e` switch, the `best` config is selected
Current: When `pio init` is used without `-e` switch, all envs in `default_envs` are created

**Comment by ivankravets** [comment]
Thank you so much for your work! There is PlatformIO IDE v2.0-beta. We wait for PIO Core 4.4 release and will release 2.0 version. Please test it https://community.platformio.org/t/platformio-ide-for-vscode-2-0-beta-help-us-with-testing/14097

**Comment by drzony** [comment]
@ivankravets The new project switcher does not handle IntelliSense like my change did. The problem is that c_cpp_properties.json contains includes for the first platform only. I'm using ESP8266 and ESP32 in one project, my solution allowed me to use vscode configuration switcher to switch between platforms and IntelliSense and other features handled it properly, with 2.0 beta I always get includes/defines for the first platform in platformio.ini. Are there any other setting that need to be enabled for it to work?

**Comment by ivankravets** [comment]
Could you try the latest Beta 6? 

- https://community.platformio.org/t/platformio-ide-for-vscode-2-0-beta-help-us-with-testing/14097/36?u=ivankravets

**Comment by drzony** [comment]
I've just installed it and the result is the same. c_cpp_properties.json still contains esp32 includes (I switched to esp8266) and the intellisense still works as if using esp32

**Comment by ivankravets** [comment]
What is your OS?

**Comment by drzony** [comment]
Windows

**Comment by ivankravets** [comment]
This is our bug with multi-config parsing. We will fix it. As a temporary solution, you can use one `platformio.ini`. Thanks for the report!

**Comment by ivankravets** [comment]
Please open PlatformIO CLI (see terminal icon on the blue bottom toolbar) and type
```
pio upgrade --dev
```

Restart VSCode.

Does it work now?

**Comment by drzony** [comment]
Yes, now it works.

**Comment by ivankravets** [comment]
Happy coding with PlatformIO! 😊🎊

**Pull request closed without merging**
